# Header
menu:
    主页: /
    所有文章: /archives
    DEMO: $J-demo
    LINKS: $J-tags
    About Me: $J-about
    # 随笔: /tags/随笔

# SubNav
subnav:
    github: "https://github.com/Tinysymphony"
    weibo: "http://weibo.com/u/3164958577/home?wvr=5"
    pixiv: "http://www.pixiv.net/member.php?id=13382232"
    zhihu: "http://www.zhihu.com/people/TinySymphony"
    #douban: "http://www.douban.com/people/45963589/"
    mail: "mailto:zjutiny@gmail.com"
    #facebook: "#"
    #google: ""
    twitter: "https://twitter.com/zjutiny"
    linkedin: "https://www.linkedin.com/profile/view?id=387499142&trk=nav_responsive_tab_profile"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: false
# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: 'UA-78495806-1'
favicon: /favicon.png

#你的头像url
avatar: "http://7xjgb0.com1.z0.glb.clouddn.com/avatar-100kb.png"
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: wytiny
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
    xl: http://xn--l4tn57c.xn--fiqs8s/
    xjp: http://www.xjp.in/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 浙江大学12级点歪科技树的CS学生，前端设计爱好者，Linux教徒…
